"""empty message

Revision ID: c38f592efcfe
Revises: 7a3cd252f86f
Create Date: 2023-12-30 22:30:51.702199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38f592efcfe'
down_revision = '7a3cd252f86f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('trainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('diets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breakfast', sa.String(length=120), nullable=False),
    sa.Column('brunch', sa.String(length=120), nullable=False),
    sa.Column('lunch', sa.String(length=120), nullable=False),
    sa.Column('dinner', sa.String(length=120), nullable=False),
    sa.Column('supper', sa.String(length=120), nullable=False),
    sa.Column('id_trainer', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_trainer'], ['trainer.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Chest', sa.String(length=120), nullable=False),
    sa.Column('shoulders', sa.String(length=120), nullable=False),
    sa.Column('arms', sa.String(length=120), nullable=False),
    sa.Column('legs', sa.String(length=120), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_trainer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_trainer'], ['trainer.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pathologies', sa.String(length=120), nullable=True))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('pathologies')

    op.drop_table('routines')
    op.drop_table('diets')
    op.drop_table('trainer')
    op.drop_table('admins')
    # ### end Alembic commands ###
